"""additional count_favorites columns

Revision ID: 02db388df410
Revises: 894d32f42260
Create Date: 2020-11-12 08:38:37.442942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02db388df410'
down_revision = '894d32f42260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('count_favorites', sa.Integer(), nullable=True))
    op.execute('UPDATE post SET count_favorites = 0')
    op.alter_column('post', 'count_favorites', nullable=False)
    op.add_column('user', sa.Column('count_favorites', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET count_favorites = 0')
    op.alter_column('user', 'count_favorites', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'count_favorites')
    op.drop_column('post', 'count_favorites')
    # ### end Alembic commands ###
