"""events

Revision ID: 0a8017f77dd0
Revises: 048d4149eb79
Create Date: 2020-12-26 08:27:37.640296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8017f77dd0'
down_revision = '048d4149eb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datestamp', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ellapsed_time', sa.Integer(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('requesting_addr', sa.Text(), nullable=True),
    sa.Column('responding_addr', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('_datestamp_index', 'event', ['datestamp'], unique=False)
    op.create_table('event_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('start_range', sa.DateTime(), nullable=True),
    sa.Column('end_range', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('_name_index', 'event_aggregate', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_name_index', table_name='event_aggregate')
    op.drop_table('event_aggregate')
    op.drop_index('_datestamp_index', table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
