"""hybrid properties added

Revision ID: 1338d1c79883
Revises: e85749a47ddc
Create Date: 2020-11-10 09:29:51.323101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1338d1c79883'
down_revision = 'e85749a47ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kabase', sa.Column('_name', sa.String(length=200), nullable=False))
    op.add_column('kabase', sa.Column('_path', sa.String(length=650), nullable=False))
    op.drop_constraint('_path_type_uniqueness', 'kabase', type_='unique')
    op.create_unique_constraint('_path_type_uniqueness', 'kabase', ['_path', 'type'])
    op.drop_column('kabase', 'path')
    op.drop_column('kabase', 'name')
    op.add_column('measure', sa.Column('_ordinal', sa.Integer(), nullable=True))
    op.drop_column('measure', 'ordinal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure', sa.Column('ordinal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('measure', '_ordinal')
    op.add_column('kabase', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('kabase', sa.Column('path', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_constraint('_path_type_uniqueness', 'kabase', type_='unique')
    op.create_unique_constraint('_path_type_uniqueness', 'kabase', ['path', 'type'])
    op.drop_column('kabase', '_path')
    op.drop_column('kabase', '_name')
    # ### end Alembic commands ###
