"""user text field

Revision ID: 1aaae7caa75f
Revises: b469eaa2d3ad
Create Date: 2020-11-10 19:48:28.067619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaae7caa75f'
down_revision = 'b469eaa2d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'text')
    # ### end Alembic commands ###
