"""favorites prop on user table

Revision ID: 209e9d8b53d3
Revises: 7c25d09b882a
Create Date: 2020-11-14 09:19:10.276015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209e9d8b53d3'
down_revision = '7c25d09b882a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
