"""added query string to HttpEvent

Revision ID: 22fc03f7127c
Revises: 51b4ed2c5016
Create Date: 2020-12-26 09:05:20.355501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fc03f7127c'
down_revision = '51b4ed2c5016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'query')
    # ### end Alembic commands ###
