"""count scores, posts, and plays

Revision ID: 236848901e48
Revises: 02db388df410
Create Date: 2020-11-12 13:49:57.090618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '236848901e48'
down_revision = '02db388df410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measure', 'visibility')

    op.add_column('post', sa.Column('count_plays', sa.Integer(), nullable=True))
    op.execute('UPDATE post SET count_plays = 0')
    op.alter_column('post', 'count_plays', nullable=False)

    op.add_column('user', sa.Column('count_posts', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET count_posts = 0')
    op.alter_column('user', 'count_posts', nullable=False)

    op.add_column('user', sa.Column('count_scores', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET count_scores = 0')
    op.alter_column('user', 'count_scores', nullable=False)

    op.add_column('user', sa.Column('count_tours', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET count_tours = 0')
    op.alter_column('user', 'count_tours', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'count_tours')
    op.drop_column('user', 'count_scores')
    op.drop_column('user', 'count_posts')
    op.drop_column('post', 'count_plays')
    op.add_column('measure', sa.Column('visibility', postgresql.ENUM('PUBLIC', 'PRIVATE', 'HIDDEN', name='visibility'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
