"""favorite relationship from score to kabase

Revision ID: 3074944665b8
Revises: 9411ed898653
Create Date: 2020-11-26 16:42:59.625075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3074944665b8'
down_revision = '9411ed898653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_content_id_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'kabase', ['content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_content_id_fkey', 'favorite', 'score', ['content_id'], ['id'])
    # ### end Alembic commands ###
