"""fixing hybrid properties

Revision ID: 556375204902
Revises: 1aaae7caa75f
Create Date: 2020-11-11 07:40:34.002856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556375204902'
down_revision = '1aaae7caa75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
