"""check that favorite changes are in sync

Revision ID: 713854b0eab3
Revises: 209e9d8b53d3
Create Date: 2020-11-15 01:47:57.950730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713854b0eab3'
down_revision = '209e9d8b53d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
