"""featured and user.is_admin

Revision ID: 87d1e8c337e5
Revises: b8c0a73c6385
Create Date: 2020-12-06 07:46:24.486861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d1e8c337e5'
down_revision = 'b8c0a73c6385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['kabase.id'], ),
    sa.ForeignKeyConstraint(['id'], ['kabase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET is_admin=false')
    op.alter_column('user', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_table('feature')
    # ### end Alembic commands ###
