"""user invites counter

Revision ID: 8e10727540ad
Revises: 713854b0eab3
Create Date: 2020-11-16 12:46:32.991501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e10727540ad'
down_revision = '713854b0eab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invites_left', sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET invites_left = 0')
    op.alter_column('user', 'invites_left', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invites_left')
    # ### end Alembic commands ###
