"""kabase unique index

Revision ID: 92db675d6a22
Revises: 1338d1c79883
Create Date: 2020-11-10 09:51:11.249049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db675d6a22'
down_revision = '1338d1c79883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('_path_type_unique_index', 'kabase', ['_path', 'type'], unique=True)
    op.drop_constraint('_path_type_uniqueness', 'kabase', type_='unique')
    op.add_column('score', sa.Column('variation_on_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'score', 'score', ['variation_on_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'variation_on_id')
    op.create_unique_constraint('_path_type_uniqueness', 'kabase', ['_path', 'type'])
    op.drop_index('_path_type_unique_index', table_name='kabase')
    # ### end Alembic commands ###
