"""test if there are changes

Revision ID: b469eaa2d3ad
Revises: 92db675d6a22
Create Date: 2020-11-10 14:10:24.685043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b469eaa2d3ad'
down_revision = '92db675d6a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
