"""added flask-sqlalchemy

Revision ID: b8c0a73c6385
Revises: 3074944665b8
Create Date: 2020-12-05 11:23:20.739687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c0a73c6385'
down_revision = '3074944665b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
