"""first

Revision ID: e85749a47ddc
Revises: 
Create Date: 2020-11-09 22:48:57.360862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85749a47ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kabase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', 'type', name='_path_type_uniqueness')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('confirmed', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'HIDDEN', name='visibility'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['kabase.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'HIDDEN', name='visibility'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['kabase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('count_plays', sa.Integer(), nullable=True),
    sa.Column('count_favorites', sa.Integer(), nullable=True),
    sa.Column('for_players', sa.Enum('OneMan', 'TwoMen', 'OneWoman', 'TwoWomen', 'OneAny', 'TwoAny', 'ManAndWoman', 'ManAndAny', 'WomanAndAny', name='forplayers'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'HIDDEN', name='visibility'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['kabase.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.Enum('Grave', 'Lento', 'Adagio', 'Adagietto', 'Andante', 'Moderato', 'Allagretto', 'Allegro', 'Vivace', 'Presto', name='tempo'), nullable=False),
    sa.Column('dynamic', sa.Enum('Fortissimo', 'Forte', 'Mezzo', 'Piano', 'Pianissimo', name='dynamic'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'HIDDEN', name='visibility'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['kabase.id'], ),
    sa.ForeignKeyConstraint(['score_id'], ['score.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measure')
    op.drop_table('score')
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('kabase')
    # ### end Alembic commands ###
