"""Allegretto spelling fix

Revision ID: fd3a5b2c9a32
Revises: f48e9ba61164
Create Date: 2020-12-21 09:01:21.319201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3a5b2c9a32'
down_revision = 'f48e9ba61164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tempo RENAME VALUE 'Allagretto' TO 'Allegretto'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tempo RENAME VALUE 'Allegretto' TO 'Allagretto'")
    # ### end Alembic commands ###
